### PR TITLE
use raw enum type in bindings

### PR DESCRIPTION
**Pull request by BusyJay**
So we don't need to define it multiple types and keep synchronous.

### CODE REVIEW

**Review by tabokie — COMMENTED** [review]
Does it really build? I thought C++-style enum can't be used in C header "c.h".

**Comment by BusyJay** [comment]
> Does it really build? I thought C++-style enum can't be used in C header "c.h".

Yes, it can be built and tested successfully. Because it's not treated as C in the build script. Instead, C++ mode is enabled during compilation and bindgen. Apparently, they are valid C++ code and can be parsed correctly.

https://github.com/BusyJay/tirocks/blob/a15458c20f24524489037c64526ce574410921cf/tirocks-sys/build.rs#L29

https://github.com/BusyJay/tirocks/blob/a15458c20f24524489037c64526ce574410921cf/tirocks-sys/build.rs#L253

**Comment by BusyJay** [comment]
Technically, you can even use C++ class with bindgen, but I don't do it because it's complicated to handle constructors and destructors. Perhaps we can use C++ bindings directly in the future when library like [autocxx](https://github.com/google/autocxx) are mature enough.

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by tabokie — APPROVED** [review]

**Pull request merged**
