### PR TITLE
tirocks-sys: update titan

### PR DESCRIPTION
**Pull request by BusyJay**

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

**Review by tabokie — APPROVED** [review]
I'm thinking could we wrap titan into a separate cargo crate? Users (many) that do not need it and can avoid downloading and building it.

**Comment by BusyJay** [comment]
> wrap titan into a separate cargo crate

I would rather not. Instead, we can make it an optional feature.

**Comment by tabokie** [comment]
> I would rather not. Instead, we can make it an optional feature.

So crates.io will cache package with different features?

**Comment by BusyJay** [comment]
> So crates.io will cache package with different features?

No, all sources will be published to crates.io. And build script can build part of sources according to features.

**Pull request merged**
